# ===============================
# = APPLICATION SERVER configurations
# ===============================   
server:
  undertow: 
    ioThreads: 15
    workerThreads: 150
    accesslog:
      enabled: true
  compression: 
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096  
  servlet:
    context-path: /haud

# ===============================
# = Hibernate datasource
# ===============================
spring:
  main:
    banner-mode: 'off' 
  resources:
    chain:
      enabled: true  
  mvc:
    favicon:
      enabled: false 
  datasource:
    url: jdbc:mysql://localhost:3306/svalinn_svc_cat2_db?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: mvrmvr
  driver-class-name: com.mysql.jdbc.Driver
# ===============================
# = JPA configurations
# ===============================  
  jpa:
    show-sql: true
    hibernate:
      show-sql: true
    generate-ddl: false
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

haud: 
  app: 
    uuid: X-HAUD-INTERNAL-UUID
  stats:  
    dumpdelay: 10000
    dumpperiod: 10000
	redispingdelay: 10000
	kafkapingdelay: 10000
    threadpoolsize: 1
  flydb:
    database-version: 5.1.17
    database-url: jdbc:mysql://localhost:3306/svalinn_svc_cat2_db?createDatabaseIfNotExist=true&useSSL=true
    database-user: root
    database-password: mvrmvr
    migrate: true
  redisson:
     ulakey: ULACache
     ulrkey: ULRCache
     trxkey: TrxCache
     subscriber:
       topic: messageQueue
     useSentinel: true
     masterAddress: redis://10.0.31.108:6379
     clientName: null
     idleConnectionTimeout: 10000
     pingTimeout: 1000
     connectTimeout: 10000
     timeout: 3000
     retryAttempts: 3
     retryInterval: 1500
     reconnectionTimeout: 3000
     subscriptionsPerConnection: 5
     subscriptionConnectionMinimumIdleSize: 1
     subscriptionConnectionPoolSize: 50
     connectionMinimumIdleSize: 10
     connectionPoolSize: 64
     threads: 16
     nettyThreads: 32
     password: mvr#1976   
     failedSlaveReconnectionInterval: 3000
     failedSlaveCheckInterval: 60000
     slaveConnectionMinimumIdleSize: 24
     slaveConnectionPoolSize: 64
     masterConnectionMinimumIdleSize: 24
     masterConnectionPoolSize: 64
     masterName: haud-produce-master       
     database: 0
     sentinelAddresses: redis://10.0.31.108:26379,redis://10.0.31.108:26380,redis://10.0.31.108:26381
  kafka:
    #bootstrapAddress: kafka1:9092
    bootstrapAddress: 191.255.15.98:9092  
    #bootstrapAddress: localhost:9092
    ConsumerConfig:
       heartbeatinterval: 5000   
       isolationlevel: read_committed 
       autoresetconfig: earliest 
       enableautoconfig: true 
       autocomitconfig: 100 
       sessiontimeout: 15000
       concurrencycount: 1 
    ProducerConfig: 
       retriesconfig: 0
       batchsizeconfig: 4096
       lingerconfig: 1
       buffermemoryconfig: 40960  
    groupId: cat2-packets
    batch:
      size: 1000
      wait: 1
      maxbytes: 500000000

    message:
      producer:
         topic:
            name: t_dec_req
      consumer:
        topic:
            name: t_req
            partitions: x-reply-partition
      listener:
        latch:
          thread:
            size: 5
  filter:
    trxcache:
      flag: true
    apid: 2
    serviceId: 1
    serviceInst: 1

# ===============================
# = Logging configurations
# ===============================
logging:
  level:    
   com.haud: DEBUG
  path: log
  file: ${logging.path}/haud-ldap-log.log
  pattern:
    file:   "%d{dd-MM-yyyy HH:mm:ss.SSS} %-1level  [%logger.%M - %L] - %msg%n"      