server:
  port: 8086
spring:
  cache:
    type: redis
  protocoldatasource:
    url: jdbc:mysql://localhost:3306/lteruledb
    username: root
    password: mvrmvr
    driver-class-name: com.mysql.jdbc.Driver
  ruledatasource:
    url: jdbc:mysql://localhost:3306/svallin_lteruledb
    username: root
    password: mvrmvr
    driver-class-name: com.mysql.jdbc.Driver  
  associationdatasource:
    url: jdbc:mysql://localhost:3306/associationdb
    username: root
    password: mvrmvr
    driver-class-name: com.mysql.jdbc.Driver   
  jpa:
    show-sql: true
    hibernate:
      show-sql: true
      ddl-auto: update
    generate-ddl: true
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
names:
  format: 
    ap: AP123    
    cat2: CAT2123
    cat3: CAT3123
    decisionModule: DM123   
haud: 
  app: 
    uuid: X-HAUD-INTERNAL-UUID
  redis:    
    host: localhost
    port: 6379
    password: mvr#1976 
    usepool: true
    timeout: 60
    cdrkey: CDRCache
    trxkey: TRXCache
    subscriber:
      topic: messageQueue
    jedis:
      pool:
        max: 5
        testOnBorrow: true
        testOnReturn: true
  kafka:
    bootstrapAddress: 191.255.15.98:9092
    groupId: packetslocal
    batch: 
      size: 1000
      wait: 1
      maxbytes: 500000000
    
    message:   
      consumer: 
        topic:
          name: t_req,t_dec_req
          partition: x-reply-partition
      producer:
        topic:
          name: t_resp
          
      listener:
        latch:
          thread:
            size: 5
protobuff:
  partials:
    size: 2    
decision:
  apid: 4    
  timeToLive: 30