server:
  port: 8086
spring:
  cache:
    type: redis
  protocoldatasource:
    url: jdbc:mysql://localhost:3306/lteruledb
    username: root
    password: mvrmvr
    driver-class-name: com.mysql.jdbc.Driver
  ruledatasource:
    url: jdbc:mysql://localhost:3306/svallin_lteruledb
    username: root
    password: mvrmvr
    driver-class-name: com.mysql.jdbc.Driver  
  associationdatasource:
    url: jdbc:mysql://localhost:3306/associationdb
    username: root
    password: mvrmvr
    driver-class-name: com.mysql.jdbc.Driver 
  decisonmoduledatasource:
    url: jdbc:mysql://localhost:3306/decision_moduledb
    username: root
    password: mvrmvr
    driver-class-name: com.mysql.jdbc.Driver   
  jpa:
    show-sql: true
    hibernate:
      show-sql: true
      ddl-auto: update
    generate-ddl: true
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
names:
  format: 
    ap: AP123    
    cat2: CAT2123
    cat3: CAT3123
    decisionModule: DM123   
haud: 
  app: 
    uuid: X-HAUD-INTERNAL-UUID
  redis:    
    host: localhost
    port: 6379
    password: mvr#1976 
    usepool: true
    timeout: 60
    cdrkey: CDRCache
    trxkey: TRXCache
    subscriber:
      topic: messageQueue
    jedis:
      pool:
        max: 5
        testOnBorrow: true
        testOnReturn: true
 redisson:
     setAddress: redis://localhost:6379
     setClientName: null
     setIdleConnectionTimeout: 10000
     setPingTimeout: 1000
     setConnectTimeout: 1000
     setTimeout: 1000
     setRetryAttempts: 3
     setRetryInterval: 1500
     setReconnectionTimeout: 3000
     setSubscriptionsPerConnection: 5
     setSubscriptionConnectionMinimumIdleSize: 1
     setSubscriptionConnectionPoolSize: 50
     setConnectionMinimumIdleSize: 10
     setConnectionPoolSize: 64
     setThreads: 15
     setNettyThreads: 150
     setPassword: mvr#1976		
  kafka:
#bootstrapAddress: 191.255.15.98:9092    
    bootstrapAddress: localhost:9092
    groupId: packetslocalMayuresh
    batch: 
      size: 1000
      wait: 1
      maxbytes: 500000000
    
    message:   
      consumer: 
        topic:
          name: t_req,t_dec_req
          partition: x-reply-partition
      producer:
        topic:
          name: t_req		  
          
      listener:
        latch:
          thread:
            size: 5
protobuff:
  partials:
    size: 2    
cron:
  processor:
    interval: 1000
  element:
    interval: 1000
  rule:
    interval: 1000      
decision:
  apid: 4    
  timeToLive: 30