# = APPLICATION SERVER configurations
# ===============================   
server:
  port: 8086 
  undertow: 
    ioThreads: 15
    workerThreads: 150
    accesslog:
      enabled: true
  compression: 
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096  
  
spring:
  protocoldatasource:
    url: jdbc:mysql://localhost:3306/lteruledb
    username: root
    password: mvrmvr
    driver-class-name: com.mysql.jdbc.Driver
  ruledatasource:
    url: jdbc:mysql://localhost:3306/svallin_lteruledb
    username: root
    password: mvrmvr
    driver-class-name: com.mysql.jdbc.Driver  
  associationdatasource:
    url: jdbc:mysql://localhost:3306/associationdb
    username: root
    password: mvrmvr
    driver-class-name: com.mysql.jdbc.Driver
 
  jpa:
    show-sql: true
    hibernate:
      show-sql: true
      ddl-auto: update
    generate-ddl: true
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
names:
  format: 
    ap: AP123    
    cat2: CAT2123
    cat3: CAT3123
    decisionModule: DM123   
haud: 
  app: 
    uuid: X-HAUD-INTERNAL-UUID
  stats:  
    dumpdelay: 10000
    dumpperiod: 10000
    redispingdelay: 10000
    kafkapingdelay: 10000
    threadpoolsize: 1
  redisson:
     cdrkey: CDRCache
     trxkey: TRXCache
     useSentinel: true
     masterAddress: redis://10.0.28.131:6379 
     clientName: null
     idleConnectionTimeout: 10000
     pingTimeout: 1000
     connectTimeout: 10000
     timeout: 3000
     retryAttempts: 3
     retryInterval: 1500
     reconnectionTimeout: 3000
     subscriptionsPerConnection: 5
     subscriptionConnectionMinimumIdleSize: 1
     subscriptionConnectionPoolSize: 50
     connectionMinimumIdleSize: 10
     connectionPoolSize: 64
     threads: 16
     nettyThreads: 32
     password: mvr#1976
     failedSlaveReconnectionInterval: 3000
     failedSlaveCheckInterval: 60000
     slaveConnectionMinimumIdleSize: 24
     slaveConnectionPoolSize: 64
     masterConnectionMinimumIdleSize: 24
     masterConnectionPoolSize: 64
     masterName: haud-produce-master       
     database: 0
     sentinelAddresses: redis://10.0.28.149:26379,redis://10.0.28.149:26380,redis://10.0.28.149:26381
  kafka:
    #bootstrapAddress: kafka1:9092
    #bootstrapAddress: localhost:9092  191.255.15.98:9092
    bootstrapAddress: localhost:9092
    ConsumerConfig:
       heartbeatinterval: 5000   
       isolationlevel: read_committed 
       autoresetconfig: earliest 
       enableautoconfig: true 
       autocomitconfig: 100 
       sessiontimeout: 15000
       concurrencycount: 1 
    ProducerConfig: 
       retriesconfig: 0
       batchsizeconfig: 4096
       lingerconfig: 1
       buffermemoryconfig: 40960  
    groupId: decision-module
    batch: 
      size: 1000
      wait: 1
      maxbytes: 500000000
    
    message:   
      consumer: 
        topic:
          name: AP-Writer-Topic,CAT2-Writer-Topic,CAT3-Writer-Topic
          partition: x-reply-partition
      producer:
        topic:
          name: Decision-Writer-Topic     
          partition: x-reply-partition
      listener:
        latch:
          thread:
            size: 5
protobuff:
  partials:
    size: 2   
cron:
  processor:
    interval: 1000
  element:
    interval: 1000
  rule:
    interval: 1000      
decision:
  apid: 4    
  timeToLive: 30
executor:
  poolSize: 5   
  waitForTaskCompleteOnShutDown: true
scheduler:
  delay: 5000 
hyperscan:
  poolSize: 5  
  