server:
  servlet:
    context-path: /haud
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    generate-ddl: true
    show-sql: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    platform: org.hibernate.dialect.MySQL8DBDialect
    url: jdbc:mysql://localhost:3306/haud_db?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: mvrmvr
