server:
  servlet:
    context-path: /haud
haud:  
  app: 
    uuid: X-HAUD-INTERNAL-UUID  
spring:
  main:
    banner-mode: off 
  mvc:
    favicon:
      enabled: false  
  datasource:
    url: jdbc:mysql://localhost:3306/haud_db?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: mvrmvr
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    generate-ddl: true
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:    
   com.haud: DEBUG
  path: log
  file: ${logging.path}/haud-ldap-log.log
  pattern:
    file:   "%d{dd-MM-yyyy HH:mm:ss.SSS} %-1level  [%logger.%M - %L] - %msg%n"