# ===============================
# = APPLICATION SERVER configurations
# ===============================   
server:
  undertow: 
    ioThreads: 15
    workerThreads: 150
    accesslog:
      enabled: true
  compression: 
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096  
  servlet:
    context-path: /haud
# ===============================
# = HAUND UUID configurations
# ===============================   
haud:  
  app: 
    uuid: X-HAUD-INTERNAL-UUID
           
protserv:
  pagable:    
    maxsize: 500
  flydb:
    database-version: 5.1.17
    database-url: jdbc:mysql://localhost:3306/haud_flydb
    database-user: root
    database-password: mvrmvr      
    migrate: true
# ===============================
# = Hibernate datasource
# ===============================
spring:
  main:
    banner-mode: 'off' 
  resources:
    chain:
      enabled: true  
  mvc:
    favicon:
      enabled: false  
  datasource:
    url: jdbc:mysql://localhost:3306/svallin_db?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: mvrmvr
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    generate-ddl: true
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
# ===============================
# = Logging configurations
# ===============================
logging:
  level:    
   com.haud: DEBUG
  path: log
  file: ${logging.path}/haud-ldap-log.log
  pattern:
    file:   "%d{dd-MM-yyyy HH:mm:ss.SSS} %-1level  [%logger.%M - %L] - %msg%n"   