server:
  servlet:
    context-path: /haud
  error:
    include-stacktrace: never

spring:
  mvc:
    favicon:
      enabled: false
        
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB  

logging:
  level:    
   com.haud: DEBUG
  path: log
  file: ${logging.path}/haud-ldap-log.log
  pattern:
    file:   "%d{dd-MM-yyyy HH:mm:ss.SSS} %-1level  [%logger.%M - %L] - %msg%n"
   
haud:  
  app: 
    uuid: X-HAUD-INTERNAL-UUID  


usrsrv:  
  ldap: 
    url: ldap://191.255.15.251:389     
    userDn: CN=mayuresh.,CN=Users,DC=matfar,DC=haud
    password: 1234567!a
    setBase: CN=Users,DC=matfar,DC=haud
    user: 
      objectclass: user
    group: 
      objectclass: group
    cn :
      objectclass: cn
    member: 
      objectclass: member
    mail: 
      attribute: mail
    distinguishedName: 
      objectclass: distinguishedName
    restrictedAttributesWhileUpdate: 
      objectclass: cn,sn,sAMAccountName,givename
    restrictedSuperUsers: 
      objectclass: mayuresh.Administrator	  
  patterns:
    password: "((?=.*[a-z])(?=.*\\d)(?=.*[A-Z])(?=.*[@#$%!]).{8,40})"
       