# ===============================
# = APPLICATION SERVER configurations
# ===============================   
server:
  undertow: 
    ioThreads: 15
    workerThreads: 150
    accesslog:
      enabled: true
  compression: 
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096  
  servlet:
    context-path: /haud
  error:
    include-stacktrace: never

spring:
  mvc:
    favicon:
      enabled: false
        
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB  

logging:
  level:    
   com.haud: DEBUG
  path: log
  file: ${logging.path}/haud-ldap-log.log
  pattern:
    file:   "%d{dd-MM-yyyy HH:mm:ss.SSS} %-1level  [%logger.%M - %L] - %msg%n"
   
haud:  
  app: 
    uuid: X-HAUD-INTERNAL-UUID  


usrsrv:  
  ldap: 
    url: ldap://191.255.15.251:389    
    userDn: CN=mayuresh.,CN=Users,DC=matfar,DC=haud
    password: 1234567!a
    setBase: CN=Users,DC=matfar,DC=haud
    user: 
      objectclass: user
    group: 
      objectclass: group
    cn :
      objectclass: cn
    member: 
      objectclass: member
    mail: 
      attribute: mail
    distinguishedName: 
      objectclass: distinguishedName
    restrictedAttributesWhileUpdate: cn,sn,sAMAccountName,givename
    restrictedSuperUsers: mayuresh.,Administrator
    restrictedMailDomains : gmail,mail    
  patterns:
    password: "((?=.*[a-z])(?=.*\\d)(?=.*[A-Z])(?=.*[@#$%!]).{8,40})"
  pagable:    
    maxsize: 500  
authsvc:
  openid:
    wellKnownConfig:
      url: http://192.168.20.34:13000/.well-known/openid-configuration
     #url: http://192.168.20.34:13000/.well-known/openid-configuration
  jwt:
    keys: 
      publicKeyB64: MIIBjDCB9gIBATANBgkqhkiG9w0BAQ0FADAPMQ0wCwYDVQQDEwRUZXN0MB4XDTE5MTAyNzE5MTc1NloXDTE5MTAyNzE5MTc1NlowDzENMAsGA1UEAxMEVGVzdDCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAqNyYLiqtrqhBuqNYhGVskKSkZTV6Jtmbb2qP7cm4ouk1opSxCvAE56KMfYMVvvx20wiRj/D2/o2sjl1onIVgcBrUaOlY455ISpNRAaKIrJweZul/IGEvISBhQCE6Flr24HJeRGMFwyS3QjmVBv2fPzL/cXl44PKBSlLdC7iU3P8CAwEAATANBgkqhkiG9w0BAQ0FAAOBgQAN08KDki5bcC3yisc7texByazi2Brpm0a70I5FnisCtbnUp81YLWyRf+X27QwS2llvCUf0KZR3xof3p17v0qyTxpBcsLMMs0M4AYcZlEz14m3HbxxuGVfUd45jB3PElsP5c/jodEzLBibc8Vd2ZNFgNhog6wQNFCCu5FqUwQDkgQ==
    header: Authorization  
    issuerUrl: http://192.168.20.34
  internalAudience: 192.168.20.34
audit:
  service:
    url: http://192.168.20.34:13030/api/audit
  enabled: true      